"""Configuration values for the Mine-Intel Streamlit frontend."""

from __future__ import annotations

import os


API_BASE_URL = os.getenv("MINE_INTEL_API_URL", "http://127.0.0.1:5000")
PREDICT_ENDPOINT = "/predict"

# UI constants
APP_TITLE = "Mine-Intel · Roof Fall Risk"
APP_DESCRIPTION = (
    "Enter the latest mining parameters to estimate the roof fall rate "
    "generated by the Mine-Intel CatBoost model."
)
DEFAULT_PRECISION = 3

