export const config = {
  apiBaseUrl: process.env.NEXT_PUBLIC_API_BASE_URL || 'http://127.0.0.1:5000',
  predictEndpoint: '/predict',
  appTitle: 'Mine-Intel · Roof Fall Risk',
  appDescription: 'Enter the latest mining parameters to estimate the roof fall rate generated by the Mine-Intel CatBoost model.',
  defaultPrecision: 3,
} as const;

