
import '../globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import { AppStateProvider } from '@/context/AppState';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AppStateProvider>
          {children}
        </AppStateProvider>
      </body>
    </html>
  )
}
